// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC05jrC8hDpZHHKOBKUaugLJVbuFfzy7a8',
    appId: '1:378908162249:web:0956263451c7cb5172f518',
    messagingSenderId: '378908162249',
    projectId: 'ezy-menu',
    authDomain: 'ezy-menu.firebaseapp.com',
    storageBucket: 'ezy-menu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0SlDr9KSf-XMWAja8rZ8gA9guNAoFBgs',
    appId: '1:378908162249:android:0e5588bc58e67c0e72f518',
    messagingSenderId: '378908162249',
    projectId: 'ezy-menu',
    storageBucket: 'ezy-menu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJShQBmETzCsM5fZATE0WBdEFbVZiBqI',
    appId: '1:378908162249:ios:4502f11b72c36bd972f518',
    messagingSenderId: '378908162249',
    projectId: 'ezy-menu',
    storageBucket: 'ezy-menu.appspot.com',
    iosClientId: '378908162249-q190djn9ekki4defrb8a3p53sm1f3poh.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuapp',
  );
}
